### ISSUE TITLE
Error: "Hot Module Replacement (HMR) is not enabled!"

### ISSUE THREAD

**Issue by MOZGIII** [pmmmwh/react-refresh-webpack-plugin#169]
I'm getting this error:

```
[React Refresh] Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to function properly.
```

I'm using `electron-forge` to drive the webpack config, and it uses `webpack-dev-server` with `hot: true` internally. Apparently, there's a kind of an init ordering issue, but `react-refresh-webpack-plugin` *wrongly* detects that hot reload is not enables.

A simple demonstration of the incorrectness of this behavior is adding `new webpack.HotModuleReplacementPlugin()` makes the error go away and the page to load, but upon the refresh the typical stack overflow error caused by two instances of hot reload plugin running occurs.

Our setup worked correctly before the update, this seems like a bug. It would be great to have an option to opt-out of this check entirely.

Unfortunately, disabling `hot` at the `webpack-dev-server` end is not an option for us, since it's under control of the `electron-forge`.

Webpack we're using is v4.
Version 0.3.3 works, version 0.4.1 has this issue.

**Comment by pmmmwh** [comment]
I'll take a look - I suspect that it has something to do with the ordering of execution. 

> Our setup worked correctly before the update, this seems like a bug. It would be great to have an option to opt-out of this check entirely.

It's kinda frustrating how various integrations have slightly different ways and timings of injecting the HMR plugin, and I do agree that the check right now is not as robust as it should be. However I still think this check acts as a good guard of usual configuration errors (the same can be said for `react-refresh/babel` config but unfortunately we cannot detect that properly).

I will take a look at various approaches to make that detection reliable - if it is really close-to-impossible then maybe I'll add the option to opt-out.

> Unfortunately, disabling `hot` at the `webpack-dev-server` end is not an option for us, since it's under control of the `electron-forge`.

I will test with a bare-bones WDS setup first - if I have a fix I'll open a PR. Would you mind help testing the PR once it's out since I am not familiar with the electron ecosystem? (Via git installations)

**Comment by pmmmwh** [comment]
> I'm using `electron-forge` to drive the webpack config, and it uses `webpack-dev-server` with `hot: true` internally. Apparently, there's a kind of an init ordering issue, but `react-refresh-webpack-plugin` _wrongly_ detects that hot reload is not enables.

Is it possible to point me to where/how they config this? How do you use the plugin with `electron-forge`?

**Comment by MOZGIII** [comment]
I think the issue is with a `preload` script. I ran the `yarn start` process under a debugger, and it shows that the `if (!context.hot)` guarding that `throw` runs twice (for renderer build) - seems like once for `main` and once for `preload` endpoint.

UPD: I can confirm that the run with `target: "electron-render"` has `hot: true`, and the run with `target: "electron-preload"` doesn't have it set at all.

**Comment by MOZGIII** [comment]
> I will test with a bare-bones WDS setup first - if I have a fix I'll open a PR. Would you mind help testing the PR once it's out since I am not familiar with the electron ecosystem? (Via git installations)

I'll be happy to help.

**Comment by pmmmwh** [comment]
> Adding a preload script should allow you to reproduce this issue. Not sure how to work around this though. Maybe allow user to pass a predicate (`(context) => bool`) to determine whether to enable plugin or not? This seems like an inflexibility of the `electron-forge` that we can't have separate webpack plugins for renderer and preload bundles.

[This](https://github.com/electron-userland/electron-forge/pull/1777) should be of interest to you.

In the mean time though, I might just add a way to disable checks, but do note that with disabled checks we cannot guarantee stuff will work (esp. HMR is not enabled for the preload script). I don't think any errors will arise, it's just some bloat no-op if branches (hopefully)

**Comment by MOZGIII** [comment]
I make it work with a patch that comments out the checks. I was getting a lot of HMR warning messages about incorrcect (or unexpected) errors. I’m not sure what was causing it, but it was a code with a gross hack, so I didn’t create an issue for that. When I have time to continue the investigation - I’ll try to debug it.

Also, I figured there must be a webpack plugin that conditionally inserts other plugins based on a predicate over the context. Sort of like fn-based webpack configuration, but at the plugin level. Electron forge only supports Object condig, andding fn config ould also solve the issue for me - and I have a PR to add it for a while now 😄

**Comment by pmmmwh** [comment]
> I make it work with a patch that comments out the checks. I was getting a lot of HMR warning messages about incorrcect (or unexpected) errors. I’m not sure what was causing it, but it was a code with a gross hack, so I didn’t create an issue for that. When I have time to continue the investigation - I’ll try to debug it.

I think it might have something to do with mismatched conditions inside the prerender script, ouch.

> Also, I figured there must be a webpack plugin that conditionally inserts other plugins based on a predicate over the context.

This is actually not very safe because all plugins should have been added before the compilation starts (cause after that hooks will run in order and will not re-fire) ... (which is also why we don't insert HMR automatically because some other integration might do it programmatically)

**Comment by MOZGIII** [comment]
I've prepared a fork of the `electron-forge-webpack-plugin` recently, and I'm planning to use it to concentrate all the patches to the upstream that I need - including a dedicated prepend script config.
This should be solved that way. Until then, I can use `0.3.3` that works fine.

**Comment by pmmmwh** [comment]
> I've prepared a fork of the `electron-forge-webpack-plugin` recently, and I'm planning to use it to concentrate all the patches to the upstream that I need - including a dedicated prepend script config.
> This should be solved that way. Until then, I can use `0.3.3` that works fine.

I'll update the `forceEnable` flag to allow you bypass all checks that we have in place, but because in v0.4 we do the processing as a part of Webpack's parsing run it might cause unintended consequences (so it might still not work if you cannot apply plugins conditionally).

**Comment by MOZGIII** [comment]
Don't bother, I think those checks are beneficial even if one would want to `forceEnable` the plugin. They do their job in warning users that things went south. So, if you want it - maybe allow anew value `forceEnable: 'no-warnings'`? I mean, without this warning I'd be more confused than with it - the code wouldn't work, but there would be no sign of a problem. With it I was able to diagnose in minutes (after I realized it's not a common problem).

**Comment by pmmmwh** [comment]
I was debating to either use `forceEnable` as a way to suppress checks, or just add a `forceSuppressErrors` flag. Maybe we could go with the latter then.

**Comment by silkfire** [comment]
I'm getting the same error while attempting to replace React Hot Reload with Fast Refresh. Not sure what I'm missing?

My webpack config:

```
const ReactRefreshPlugin = require('@pmmmwh/react-refresh-webpack-plugin');

...

      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        resolve: {
          extensions: ['.js', '.jsx'],
        },
        use: [
          {
            loader: 'babel-loader',
            options: {
              envName: 'development',
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new ReactRefreshPlugin(),
  ],
});
```

And in `.babelrc`:

```
"plugins": [
   "react-refresh/babel"
]
```

**Comment by pmmmwh** [comment]
> I'm getting the same error while attempting to replace React Hot Loader with Fast Refresh. Not sure what I'm missing?
> 
> My webpack config:
> 
> ```
> const ReactRefreshPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
> 
> ...
> 
>       {
>         test: /\.jsx?$/,
>         exclude: /node_modules/,
>         resolve: {
>           extensions: ['.js', '.jsx'],
>         },
>         use: [
>           {
>             loader: 'babel-loader',
>             options: {
>               envName: 'development',
>             },
>           },
>         ],
>       },
>     ],
>   },
>   plugins: [
>     new ReactRefreshPlugin(),
>   ],
> });
> ```
> 
> And in `.babelrc`:
> 
> ```
> "plugins": [
>    "react-refresh/babel"
> ]
> ```

What integration are you using (WDS/WHM/WPS)?

Did you enable hot module replacement for Webpack?

**Comment by silkfire** [comment]
I assume it would be WDS, as I'm using `webpackDevMiddleware`.

**Comment by yyynnn** [comment]
@silkfire well there is no clear instructions in README or example projects

**Comment by pmmmwh** [comment]
@silkfire

> Perhaps the guide could state the importance of enabling HMR, as I did not get it to work by just blindly following it? 

I am working on a docs rewrite - the current docs were written when this plugin only targeted webpack-dev-server, so there was no concerns over including bits and pieces.

@yyynnn

> well there is NO clear instructions in README or example projects

I'm not sure what is not clear for you - there are example projects for all integrations we support in the `examples` foldee. Can you suggest how we can improve?

> in my case `path` method - resolve/join in webpack config did the bad stuff

I'm not sure what break for you - Webpack docs did explicitly state that using absolute paths are better than relative ones.

> defining wds config via webpack breaks all the things

Again, the are not supposed to break. What happened in your setup? I'm open to issue reports with more context.

**Comment by pmmmwh** [comment]
Closed as the new docs have been merged to mention this scenario - feel free to open a new issue if you see this pop up again.
