### ISSUE TITLE
Webpack-dev-server always triggering full page reload

### ISSUE THREAD

**Issue by morbidick** [pmmmwh/react-refresh-webpack-plugin#186]
Hi,
I integrated this plugin in a webpack-dev-server running in parallel to an expressjs server doing SSR. To get it working without always triggering a full page refresh i needed to add:
```js
  if (module.hot) {
    module.hot.accept();
  }
```
Do you have any Idea why? I would love to do a small PR to the Readme :)

**Comment by pmmmwh** [comment]
I'm not sure about how your app is being architect so I cannot comment.

However - a full page refresh would indicate that this plugin wasn't able to do its job, or referential equality between React instances failed. My gut feeling is that the snippet shown should not be needed if this plugin is being wired up correctly.

Does HMR work for you? Maybe you also need the plugin for serverside? I am not familiar with custom SSR alongside WDS, and would need more information about the architecture to properly diagnose the problem.

**Comment by morbidick** [comment]
Hi @pmmmwh,
thank you for your input, after reading some of the other issues i discovered 3 points that i fixed, i'm not sure which one it was in the end but maybe it helps someone else:

* the react production version was mistakenly bundled
* babel was running without `preset-env`
* The entrypoint had the whole App skeleton in it instead of just doing `hydrate(<App prerenderedState={state} />, 'mountpoint')

I wanna take the chance to thank you for this awesome plugin, it brought as the awesome dev experience from CRA or Zeit (including the nice error overlay) with a custom Setup <3

**Comment by pmmmwh** [comment]
Glad that you fixed your issue! I've always wanted to get a simple custom SSR example in this repo but I never got to do it ... Maybe I should do it some time soon.

Regarding your fixes though, I think point 1 is the most crucial - the production build does not have dev tools hook setup so Fast Refresh would essentially be no-op.

**Comment by garand** [comment]
@pmmmwh I'm having a similar issue with my React project... no SSR happening, just using WDM and WHM.

The fast refresh works awesome for every file EXCEPT the index file, unless I add that code snippet from @morbidick. I have the babel plugin and all config setup to match the docs. 🤔 Any ideas?

**Comment by pmmmwh** [comment]
> @pmmmwh I'm having a similar issue with my React project... no SSR happening, just using WDM and WHM.
> 
> The fast refresh works awesome for every file EXCEPT the index file, unless I add that code snippet from @morbidick. I have the babel plugin and all config setup to match the docs. 🤔 Any ideas?

Hi, the index file will never be able to be reloaded - it has no exports and we are quite certain that it contains side effects. That code snippet will only silence the bail out, but you still do not have adequate cleanup to handle the reload of that file (for example, the `ReactDOM.render` probably will need to remount the whole tree?)

**Comment by garand** [comment]
@pmmmwh Yep, that makes total sense. Thanks for explaining it that way. 👍
