### ISSUE TITLE
Error in create-react-app referencing this plugin

### ISSUE THREAD

**Issue by colinsteidtmann** [pmmmwh/react-refresh-webpack-plugin#395]
I'm getting an error when running my react app newly created using create-react-app. Is this plugin the cause?

Reproduce:

npx create-react-app my-app
cd my-app
yarn start

yarn version: 1.22.10

Error: Failed to Compile
./src/index.js 1:43
Module parse failed: Unexpected token (1:43)
File was processed with these loaders:

./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
$RefreshRuntime$ = require('/Volumes/Colin's Mac/seeifitworks2/node_modules/react-refresh/runtime.js');
| $RefreshSetup$(module.id);
|

**Comment by pmmmwh** [comment]
It might be a bug of ours, but I'm unsure what version of CRA is currently on.

**Comment by KutnerUri** [comment]
I'm getting this now (outside of CRA).
I just add a new file to the project, and I'm getting the `unexpected token` error.

Any idea why this is happening?
It only happens when I add new files and load them with `react-fast-refresh`. When I restart the project it works fine.
Any reason it shouldn't load using the regular webpack loaders?

**Comment by KutnerUri** [comment]
after some investigation, it seems to be happening in `v0.4.3`
I reverted to `0.4.2` and things seems to be working, though I had to add a Webpack alias to resolve `react-refresh/runtime` manually.

It doesn't seem like a good idea, since we're using Webpack 5, and 0.4.3 is supposed to improve compatibility with it.

@pmmmwh any idea what is this bug?

We have a pretty advanced use case, with two separate folders.
We wrap Webpack with our tool, and use it's JS API to compile other projects:
```
target project/
	node_modules/
	src/
		file.tsx

bit-project/
	node_modules/
		webpack
		@pmmmwh/react-refresh-webpack-plugin
		react-refresh
	src/
		webpack/
			webpack.config.ts
```

**Comment by pmmmwh** [comment]
Can you print the whole error?

**Comment by KutnerUri** [comment]
This is the error:

```
ERROR in ./src/components/react04.composition.tsx 8:9
Module parse failed: Unexpected token (8:9)
File was processed with these loaders:
 * ../../bit-bin/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ../../bit-bin/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export function BasicReact01() {
|   // return null;
>   return <React01 text="hello from React02" />;
| }
| 
 @ ./node_modules/.cache/bit/teambit.preview/preview/teambit.react/react/__compositions-1623588279124.js 25:306-402
```

I tried `0.5.0-rc.0` and `0.4.2`, they both don't work.
It's something in our code, I just need a clue.
I will try to debug the loaders and see what is being used.

**Comment by pmmmwh** [comment]
Seems like you're missing the transform for JSX.

**Comment by KutnerUri** [comment]
yes, but Webpack is loading the correct loaders.
I added `inspect-loader` to each of the rules, and got this:
```
loading "/Users/kutner/projects/temp/add-compo-bug/my-scope/react02/react3.compositions.tsx" with "preset-react-app" loader
	file content ["import React from 'react';\nimport { React02 } from './react02';\n\nexport const BuggyFile = () => (\n  <div>world hello!</div>\n);\n"]
```

I'm thinking the fast-refresh-plugin is somehow using it's own babel configuration, instead of the loaders.
Or, that it has something to do with the `.js` link file I'm using to dynamically load the files. :S

here is my configuration: (I have more loaders, but I removed them locally to test)
```tsx
export default {
rules: [
	{
		test: /\.m?js/,
		resolve: {
			fullySpecified: false,
		},
	},
	{
		test: /\.(mjs|js|jsx|tsx|ts)$/,
		exclude: [/node_modules/, /dist/],
		include: WORKDIR,
		resolve: { fullySpecified: false },
		use: [
			{
				loader: require.resolve("babel-loader"),
				options: {
					babelrc: false,
					configFile: false,
					presets: [require.resolve("babel-preset-react-app")],
					plugins: [require.resolve("react-refresh/babel")],
				},
			}
		],
	},
	{
		test: [ /\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/, /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/ ],
		type: "asset",
	},
	{
		test: styleRegex,
		//   ...
	},
],
plugins: [
	new ReactRefreshWebpackPlugin({
		include: [/\.(js|jsx|tsx|ts)$/],
		exclude: [/dist/, /node_modules/],
	})
]
}
```

**Comment by pmmmwh** [comment]
Remove the duplicated `m?js` rule - that should fix the issue.

**Comment by KutnerUri** [comment]
@pmmmwh yes, it fixed it. THANKS!
(I used an `include` rule to limit the loader, since I needed it as a workaround for another package)

This behavior is a little weird. Webpack allows more than one rule to apply loaders to the same resource.
(For example, we apply `source-map-loader` to all modules, with `enforce: 'pre'`)
I would expect `react-refresh` to behave the same.
Is this possible to implement?

**Comment by pmmmwh** [comment]
This has nothing to do with react refresh.

It is the order of loaders that matters. You should tweak the loaders in a way such that anything out of your loader chain is perfectly transpiled. We simply post-process everything after all loaders have ran.

**Comment by KutnerUri** [comment]
I think Webpack 4/5 allows multiple rules? that's why we have `rules.oneof`.

Regardless, I'm uncommenting my webpack config and I'm still getting this error.
I made sure this time that only 1 rule is loading the code.

It seems to be coming from this babel plugin:
```ts
{
  test: /\.(mjs|js|jsx|tsx|ts)$/,
  exclude: [/node_modules/, /dist/],
  include: workDir,
  // TODO - this should be handled by the general `resolve.extensions` option
  resolve: { fullySpecified: false },

  loader: require.resolve('babel-loader'),
  options: {
    babelrc: false,
    configFile: false,
    presets: [ require.resolve('babel-preset-react-app') ],
    plugins: [
        require.resolve('react-refresh/babel'),

        // problematic babel loader here:
        [require.resolve('@teambit/react.babel.bit-react-transformer'), { componentFilesPath: fileMapPath }],
    ],
  },
```

I will debug the loader.
Any idea why it's behaving differently when hot loading the file?

**Comment by pmmmwh** [comment]
What kind of files are you adding in? It just seems like the JSX transform is not being used/resolved properly in your configuration, and that is most likely unrelated to the use of RR.

**Comment by KutnerUri** [comment]
regular tsx files.
We're doing a storybook style project, and we load all components from `*.composition.tsx` files.

```tsx
// src/react02/wakka.composition.tsx
import React from 'react';

export const WorkForWork = () => (
  <div>world hello!</div>
);
```

**Comment by pmmmwh** [comment]
If you can provide a reproduction maybe I can take a look at it, otherwise I can't really offer much more help.

**Comment by KutnerUri** [comment]
oomph, it will be difficult with how complicated the project is. But probably for the best, I'm on it.

**Comment by KutnerUri** [comment]
ok I reproduced it. It seems to be coming from our custom babel plugin :(
`@teambit/react.babel.bit-react-transformer`

Now that I reproduced it in a standalone project, it happens also during `build`.
At least it's consistent.

I'm investigating why the plugin is causing this. Maybe it's running before `babel-preset-react-app`, and I need to enable specific JSX support in the plugin?

You can take a look at the reproduction here:
https://github.com/KutnerUri/reproduce-webpack-bug

**Comment by CyberCookie** [comment]
Stumbled upon the very same issue
Not sure it has something to do with loaders order
The only loader related to js i'm using is **esbuild**

Repro case is a very simple and in my case it is related to a project folder structure:

  - produces_error.jsx
  - src
      - entrypoint.js
      - works_as_expected.jsx

If i'm importing a sibling or nested (related to entrypoint) files - it works as expected
But if i'm trying to import something from above level - the error appears

Maybe there were some breaking changes between **0.4.3** and **0.4.2**  ?

**Comment by pmmmwh** [comment]
> Stumbled upon the very same issue
> Not sure it has something to do with loaders order
> The only loader related to js i'm using is **esbuild**
> 
> Repro case is a very simple and in my case it is related to a project folder structure:
> 
>     * produces_error.jsx
> 
>     * src
>       
>       * entrypoint.js
>       * works_as_expected.jsx
> 
> 
> If i'm importing a sibling or nested (related to entrypoint) files - it works as expected
> But if i'm trying to import something from above level - the error appears

What error? Can you create a repo for the repro case?

**Comment by KutnerUri** [comment]
@CyberCookie - some rules might be only applying to `/src`, check your configuration.
Maybe the `.bablerc` (or hidden babel config) is transpiling `jsx` only inside src, but `react-refresh` also includes files out of src?

**Comment by CyberCookie** [comment]
@KutnerUri  @pmmmwh Sorry guys, false alarm 🤦
Problem was in webpack config -> rule -> include

Everything works good

**Comment by LiZ2z** [comment]
same error:
```
ERROR in ./src/App.tsx 59:13
Module parse failed: Unexpected token (59:13)
File was processed with these loaders:
 * ../../node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ../../node_modules/cache-loader/dist/cjs.js
 * ../../node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| _c = App;
| export default App;
> const a = 0 ?? 1;
|
| var _c;
 @ ./src/main.tsx 12:0-24 15:52-55
```
webpack.config.js :


![image](https://user-images.githubusercontent.com/30578440/130001060-0e809f41-fa2b-4a15-aa71-336b9cf31150.png)

and package.json:
```JSON
"@pmmmwh/react-refresh-webpack-plugin": "^0.4.3"
```
